# docker-compose.yml
version: "3.9"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6379"

  app:
    build: .
    ports:
      - "6969:6969"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

